# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VSTS Flow Metrics' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VSTS Flow Metrics
  pod 'AppCenter'

  target 'VSTS Flow MetricsTests' do
    inherit! :search_paths

  end

  target 'VSTS Flow MetricsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
